// Generates src/imports-generated.ts from the import lists produced by
// `wasm-objdump -x edgejs.wasm`.  Run with: npm run gen:napi-stubs
//
// Per-namespace default return values matter:
//   - napi.*        → returns 0 (napi_ok) — safe during discovery
//   - wasi*.*       → returns 52 (ERRNO_NOSYS) — fails loudly, never lies success
//   - env.*         → returns 0 — these are uv stubs, "no info" is reasonable
//
// Every call is recorded into a structured trace by the runtime (see
// worker.ts).  Implementations supplied via the `overrides` argument
// replace the default stub for that symbol.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const namespaces = [
  { ns: "napi", file: "imports-napi.txt", defaultRet: "0" },
  { ns: "napi_extension_wasmer_v0", file: "imports-napi-ext.txt", defaultRet: "0" },
  { ns: "wasi_snapshot_preview1", file: "imports-wasi.txt", defaultRet: "52" },
  { ns: "wasix_32v1", file: "imports-wasix.txt", defaultRet: "52" },
  { ns: "env", file: "imports-env.txt", defaultRet: "0" },
];

const orphan = { ns: "wasi", symbols: ["thread-spawn"], defaultRet: "-1" };

function readSymbols(path) {
  return readFileSync(resolve(root, path), "utf8")
    .split("\n").map((s) => s.trim()).filter(Boolean);
}

function jsName(ns) { return "ns_" + ns.replace(/[^a-zA-Z0-9_]/g, "_"); }

const lines = [];
lines.push("// AUTO-GENERATED by scripts/gen-stubs.mjs — do not edit by hand.");
lines.push("// Regenerate after rebuilding edgejs.wasm.");
lines.push("//");
lines.push("// #!~debt namespace-default fallbacks: every entry in this file uses an");
lines.push("// override if one exists, otherwise falls through to a per-namespace");
lines.push("// default-return stub (napi=0, wasi*=52 ENOSYS, env=0, wasi.thread-spawn=-1).");
lines.push("// 'Implemented' here means 'has a callable function with the right arity' —");
lines.push("// NOT that the function does anything semantically correct.  Edge can run");
lines.push("// for a while before tripping over a fallback, so a clean trace doesn't");
lines.push("// mean the implementation is right.  See NOTES.md tech-debt catalog for");
lines.push("// the counts of real-impl vs fallback per namespace.");
lines.push("");
lines.push("import type { HostOverrides, TraceRecorder } from './imports-types';");
lines.push("");
lines.push("export function buildImports(");
lines.push("  memory: WebAssembly.Memory,");
lines.push("  overrides: HostOverrides,");
lines.push("  trace: TraceRecorder,");
lines.push("): WebAssembly.Imports {");
lines.push("  function makeStub(ns: string, sym: string, defaultRet: number) {");
lines.push("    return (...args: unknown[]) => { trace(ns, sym, args, defaultRet, true); return defaultRet; };");
lines.push("  }");
lines.push("  function wrapImpl(ns: string, sym: string, fn: Function) {");
lines.push("    return (...args: unknown[]) => {");
lines.push("      let ret: unknown;");
lines.push("      let threw: unknown = undefined;");
lines.push("      try { ret = (fn as Function)(...args); }");
lines.push("      catch (e) { threw = e; throw e; }");
lines.push("      finally { trace(ns, sym, args, threw === undefined ? ret : `THROW:${String(threw)}`, false); }");
lines.push("      return ret;");
lines.push("    };");
lines.push("  }");
lines.push("  const imports: WebAssembly.Imports = {};");
lines.push("");

for (const { ns, file, defaultRet } of namespaces) {
  const symbols = readSymbols(file).map((s) => s.slice(ns.length + 1));
  lines.push(`  // ${ns}: ${symbols.length} functions (default ret = ${defaultRet})`);
  lines.push(`  const ${jsName(ns)}: WebAssembly.ModuleImports = {};`);
  if (ns === "env") lines.push(`  ${jsName(ns)}.memory = memory;`);
  for (const sym of symbols) {
    lines.push(
      `  ${jsName(ns)}[${JSON.stringify(sym)}] = (overrides[${JSON.stringify(ns)}]?.[${JSON.stringify(sym)}] ? wrapImpl(${JSON.stringify(ns)}, ${JSON.stringify(sym)}, overrides[${JSON.stringify(ns)}]![${JSON.stringify(sym)}]!) : makeStub(${JSON.stringify(ns)}, ${JSON.stringify(sym)}, ${defaultRet})) as never;`,
    );
  }
  lines.push(`  imports[${JSON.stringify(ns)}] = ${jsName(ns)};`);
  lines.push("");
}

lines.push(`  // ${orphan.ns}: ${orphan.symbols.length} functions (default ret = ${orphan.defaultRet})`);
lines.push(`  const ${jsName(orphan.ns)}: WebAssembly.ModuleImports = {};`);
for (const sym of orphan.symbols) {
  lines.push(
    `  ${jsName(orphan.ns)}[${JSON.stringify(sym)}] = (overrides[${JSON.stringify(orphan.ns)}]?.[${JSON.stringify(sym)}] ? wrapImpl(${JSON.stringify(orphan.ns)}, ${JSON.stringify(sym)}, overrides[${JSON.stringify(orphan.ns)}]![${JSON.stringify(sym)}]!) : makeStub(${JSON.stringify(orphan.ns)}, ${JSON.stringify(sym)}, ${orphan.defaultRet})) as never;`,
  );
}
lines.push(`  imports[${JSON.stringify(orphan.ns)}] = ${jsName(orphan.ns)};`);
lines.push("");

lines.push("  return imports;");
lines.push("}");
lines.push("");

writeFileSync(resolve(root, "src/imports-generated.ts"), lines.join("\n"));
console.log("wrote src/imports-generated.ts");
