[package]
entrypoint = "edgejs-quickjs"
name = "sadhbh-c0d3/edgejs-quickjs"
description = "Edge.js with an embedded QuickJS N-API provider"
version = "0.0.2"

# [fs]
# "/node-lib" = "./lib"
[fs]
"/usr/local/ssl" = "./ssl-certs"

[[module]]
name = "edge"
source = "./build-quickjs-wasix/edgejs.wasm"

[[command]]
name = "edge"
module = "edge"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "edge"
# env = ["EDGEJS_LIB_DIR=/node-lib"]
