[package]
name = "sadhbh-c0d3/edgejs-quickjs"
version = "0.0.5"
description = "Edge.js with an embedded QuickJS N-API provider"
entrypoint = "edgejs-quickjs"

[fs]
"/usr/local/ssl" = "./ssl-certs"

[[module]]
name = "edge"
source = "./build-quickjs-wasix/edgejs.wasm"

[[command]]
name = "edge"
module = "edge"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "edge"
